#!/usr/bin/env bash

#
# Install git
#

SUDO=${CH_SUDO:-sudo}

if [ -x "$(command -v pacman)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO pacman -S --needed --noconfirm git
elif [ -x "$(command -v apt)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO apt install git -y
fi

#
# Clone Mistral
#

git clone --depth 1 https://github.com/MistralDev/Mistral

#
# Run Mistral's build script
#

pushd Mistral
$SUDO chmod +x toolbox.sh
bash ./toolbox.sh -b
popd